language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install protobuf-c-compiler libprotobuf-c0-dev libncurses5-dev -qq
script: make
notifications:
  email: false
  irc:
    channels:
      - "irc.atw-inter.net#udpgame"
    use_notice: true
    skip_join: true
    template: "%{message} %{build_url}"
    on_success: change
    on_failure: change
