language: c
compiler: gcc
script: make
notifications:
  email: false
  irc:
    channels:
      - "irc.atw-inter.net#udpgame"
    use_notice: true
    skip_join: true
    template: "%{message} %{build_url}"
    on_success: change
    on_failure: change
